# moved to github actions for build

when:
  branch: master

steps:
  lint-and-build:
    image: golang:1.22
    pull: true
    environment:
      CGO_ENABLED: 0
      GOOS: "linux"
      GOARCH: "amd64"
    commands:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - golangci-lint version
      - golangci-lint run
      - go build -a -tags netgo -ldflags '-w' .

  #test:
  #  image: golang:1.21
  #  commands:
  #    - go test -cover ./...

  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: gowerstreet/slack
      tags:
        - latest
        - "${CI_PIPELINE_NUMBER}"
      platforms:
        - linux/amd64

  
  slack-failure:
    image: gowerstreet/slack:latest
    pull: true
    settings:
      status: failure
      description: "Slack plugin for Woodpecker"
      webhook:
        from_secret: slack_webhook
    when:
      status: failure

  slack-release:
    image: gowerstreet/slack:${CI_PIPELINE_NUMBER}
    settings:
      status: success
      description: "Slack plugin for Woodpecker"
      webhook:
        from_secret: slack_webhook
    when:
      event: push
      branch: master
      status: success
